MusinsaProduct/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('erp.urls')),
]

erp/urls.py
from django.urls import path
from . import views

app_name = 'erp'

urlpatterns = [
    path('', views.home, name='home'),
    path('erp/', views.product_list, name='product_list'),
    path('erp/create/', views.product_create, name='product_create'),
    path('erp/inbound/<int:product_id>', views.inbound_create, name='inbound_create'),
    path('erp/outbound/<int:product_id>', views.outbound_create, name='outbound_create'),
    path('erp/inventory/<int:product_id>', views.inventory, name='product_inventory'),
]

erp/models.py
import datetime

from django.db import models


# Create your models here.
class Product(models.Model):
    """
    상품 모델입니다.
    상품 코드, 상품 이름, 상품 설명, 상품 가격, 사이즈 필드를 가집니다.
    """
    code = models.CharField(max_length=10)
    name = models.CharField(max_length=10)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=0)
    sizes = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'Xtra Large'),
        ('F', 'Free'),
    )
    size = models.CharField(choices=sizes, max_length=2)
    stock_quantity = models.PositiveIntegerField(default=0)
    """
    choices 매개변수는 Django 모델 필드에서 사용하는 매개변수 중 하나로 
    해당 필드에서 선택 가능한 옵션을 지정하는 역할을 합니다. 
    변수를 통해 튜플 리스트를 받으면 첫번째 요소는 실제 DB에 저장되는 값이 되고,
    두번째 요소는 사용자가 볼 수 있는 레이블(옵션의 이름 됩니다.
    """

    def __str__(self):
        return self.code

    def save(self, *args, **kwargs):
        # 생성될 때 stock quantity를 0으로 초기화 로직
        if not self.id:  # 새로운 인스턴스인 경우에만 stock_quantity를 초기화합니다.
            self.stock_quantity = 0
        super().save(*args, **kwargs)


class Inbound(models.Model):
    """
    입고 모델입니다.
    상품, 수량, 입고 날짜, 금액 필드를 작성합니다.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=3, decimal_places=0)
    inbound_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=0)

    def __str__(self):
        return f"{self.product} - {self.quantity} - {self.amount}"

    def save(self, *args, **kwargs):
        self.amount = self.quantity * self.product.price
        super().save(*args, **kwargs)


class Outbound(models.Model):
    """
    입고 모델입니다.
    상품, 수량, 입고 날짜, 금액 필드를 작성합니다.
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=3, decimal_places=0)
    outbound_date = models.DateField()
    amount = models.DecimalField(max_digits=10, decimal_places=0)

    def __str__(self):
        return f"{self.product} - {self.quantity} - {self.amount}"

    def save(self, *args, **kwargs):
        self.amount = self.quantity * self.product.price
        super().save(*args, **kwargs)


class Inventory(models.Model):

    """
    창고의 제품과 수량 정보를 담는 모델입니다.
    상품, 수량 필드를 작성합니다.
    작성한 Product 모델을 OneToOne 관계로 작성합시다.
    """

    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    stock_quantity = models.PositiveIntegerField(default=0)
    #
    # def save(self, *args, **kwargs):
    #     self.stock_quantity = self.product.stock_quantity
    #     super().save(*args, **kwargs)

erp/forms.py
from django import forms
from .models import Product, Inbound, Outbound


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'code', 'description', 'price', 'size']
        labels = {
            'name': '제품명',
            'code': '제품코드',
            'description': '설명',
            'price': '가격',
            'size': '사이즈'
        }


class InboundForm(forms.ModelForm):
    class Meta:
        model = Inbound
        fields = ['quantity']
        labels = {
            'quantity': '수량'
        }


class OutboundForm(forms.ModelForm):
    class Meta:
        model = Outbound
        fields = ['quantity']
        labels = {
            'quantity': '수량'
        }

erp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.utils import timezone
from .models import Product, Inventory
from .forms import ProductForm, InboundForm, OutboundForm


# Create your views here.
def home(request):
    user = request.user.is_authenticated
    if user:
        return redirect('/erp')
    else:
        return redirect('/sign-in')


@login_required
def product_list(request):
    products = Product.objects.all()
    return render(request, 'erp/home.html', {'products': products})


@login_required
def product_create(request):
    # 상품 등록 view
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ProductForm()
    return render(request, 'erp/create.html', {'form': form})


@login_required
@transaction.atomic
def inbound_create(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = InboundForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.inbound_date = timezone.now()
            answer.product = product
            product.stock_quantity += answer.quantity
            product.save()
            answer.save()
            return redirect('erp:inbound_create', product_id=product.id)
    else:
        form = InboundForm()
        context = {'product': product, 'form': form}
    return render(request, 'erp/inbound.html', context)


@login_required
@transaction.atomic
def outbound_create(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = OutboundForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.outbound_date = timezone.now()
            answer.product = product
            product.stock_quantity -= answer.quantity
            product.save()
            answer.save()
            return redirect('erp:outbound_create', product_id=product.id)
    else:
        form = OutboundForm()
        context = {'product': product, 'form': form}
    return render(request, 'erp/outbound.html', context)


@login_required
def inventory(request, product_id):
    """
    inbound_create, outbound_create view에서 만들어진 데이터를 합산합니다.
    Django ORM을 통하여 총 수량, 가격등을 계산할 수 있습니다.
    """
    product = get_object_or_404(Product, pk=product_id)
    inven = Inventory.objects.filter(product=product).first()
    if not inven:
        inven = Inventory(product=product)
    total_inbounds_quantity = 0
    total_inbounds_price = 0
    total_outbounds_quantity = 0
    total_outbounds_price = 0
    # 총 입고 수량, 가격 계산
    inbounds = product.inbound_set.all()
    for inbound in inbounds:
        total_inbounds_quantity += inbound.quantity
        total_inbounds_price += inbound.amount

    # 총 출고 수량, 가격 계산
    outbounds = product.outbound_set.all()
    for outbound in outbounds:
        total_outbounds_quantity += outbound.quantity
        total_outbounds_price += outbound.amount
    inven.stock_quantity = total_inbounds_quantity - total_outbounds_quantity
    inven.save()

    context = {'inventory': inven,
               'product': product,
               'inbounds': inbounds,
               'outbounds': outbounds,
               'total_inbounds_quantity': total_inbounds_quantity,
               'total_outbounds_quantity': total_outbounds_quantity,
               'total_inbounds_price': total_inbounds_price,
               'total_outbounds_price': total_outbounds_price,
               }

    return render(request, 'erp/inventory.html', context)

templates/erp/create.html
{% extends 'base.html' %}

{% block content %}
    <h1>상품 생성</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">생성</button>
    </form>
{% endblock %}

templates/erp/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>상품 리스트</h1>
    <ul>
    {% for product in products %}
        <li>{{ product.name }} - {{ product.code }} - {{ product.description }} - {{ product.price }} - {{ product.size }} - {{ product.stock_quantity }}</li>
        <a href="{% url 'erp:product_inventory' product.id %}" class="btn btn-secondary">인벤토리</a>
        <a href="{% url 'erp:inbound_create' product.id %}" class="btn btn-secondary">입고</a>
        <a href="{% url 'erp:outbound_create' product.id %}" class="btn btn-secondary">출고</a>
    {% endfor %}
    </ul>
    <a href="{% url 'erp:product_create' %}" class="btn btn-secondary">상품 생성 페이지 </a>
{% endblock %}

templates/erp/inbound.html
{% extends 'base.html' %}

{% block content %}
    <h1>입고</h1>
    <h3>{{ product.name }} - {{ product.code }} - {{ product.description }} - {{ product.price }} - {{ product.size }} - {{ product.stock_quantity }}</h3>
    <form action="{% url 'erp:inbound_create' product.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% include "form_errors.html" %}
        <button type="submit">입고</button>
    </form>
{% endblock %}

templates/erp/inventory.html
{% extends 'base.html' %}

{% block content %}
    <h1>인벤토리</h1>
    <h3>{{ product.name }} - {{ product.code }} - {{ product.size }}</h3>
    <ul>
    <p>입고목록</p>
    {% for inbound in inbounds %}
        <li>{{ inbound.quantity }} - {{ inbound.amount }} - {{ inbound.inbound_date }}</li>
    {% endfor %}
    </ul>
    <ul>
    <p>출고목록</p>
    {% for outbound in outbounds %}
        <li>{{ outbound.quantity }} - {{ outbound.amount }} - {{ outbound.outbound_date }}</li>
    {% endfor %}
    </ul>
    <p>총 입고 수량: {{ total_inbounds_quantity }}</p>
    <p>총 입고 금액: {{ total_inbounds_price }}</p>
    <p>총 출고 수량: {{ total_outbounds_quantity }}</p>
    <p>총 출고 금액: {{ total_outbounds_price }}</p>
    <p>현 재고 수량: {{ inventory.stock_quantity }}</p>
{% endblock %}

templates/erp/outbound.html
{% extends 'base.html' %}

{% block content %}
    <h1>출고</h1>
    <h3>{{ product.name }} - {{ product.code }} - {{ product.description }} - {{ product.price }} - {{ product.size }} - {{ product.stock_quantity }}</h3>
    <form action="{% url 'erp:outbound_create' product.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% include "form_errors.html" %}
        <button type="submit">출고</button>
    </form>
{% endblock %}